### ISSUE TITLE
how to make train/test images?

### ISSUE THREAD

**Issue by jeremywrightkim** [tenstep/Randomforest_Hand_Detector#1]
maybe your `test.png` file consist of `B: 0~255 / G: 0~7 / R: 0`. 

In general depth image have only 1 channel.

But you use `g channel` for evaluate background depth in your code.
`if (res.at<Vec3b>(i, j)[0] + (res.at<Vec3b>(i, j)[1] << 8) < BACKGROUND_DEPTH)`

What are the criteria for creating a `g channel`?
Can you explain more detail?

**Comment by xingyizhou** [comment]
Hi jeremywrightkim, 
  Thanks for your interest on my projects. I am not sure I have correctly understood your question. Do you mean how to convert the RGB image into depth image? The RGB image in this project is just a representation of depth image, which uses `B channel` to store the lower 8 bits for the depth value and `G channel` to store the upper 8 bits. It follows the protocol described in NYU hand dataset (http://cims.nyu.edu/~tompson/NYU_Hand_Pose_Dataset.htm#download). 

Best, 
Xingyi

**Comment by jeremywrightkim** [comment]
Thank you. I understood.
